name: Build & Publish Windows EXEs

on:
  workflow_dispatch:
    inputs:
      tag_name:
        required: true
        type: string
        description: "The tag name to release (e.g. v1.2.3)"

permissions:
  contents: write

jobs:
  build-and-publish:
    name: Build & Publish (win-x64)
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup .NET
        uses: actions/setup-dotnet@v3
        with:
          dotnet-version: "10.0.x"

      - name: Run build.cmd
        shell: cmd
        run: .\build.cmd

      - name: Create zip of publish folder
        shell: pwsh
        env:
          TAG: ${{ inputs.tag_name }}
          REPO: ${{ github.repository }}
        run: |
          $repoSafe = $env:REPO
          $zipName = "$repoSafe-$($env:TAG).zip"
          Write-Host "Creating $zipName from ./publish/*"
          $destination = Join-Path -Path $PWD -ChildPath $zipName
          Compress-Archive -Path (Join-Path $PWD 'publish\*') -DestinationPath $destination -Force

          Add-Content -Path $env:GITHUB_ENV -Value "ZIP_NAME=$zipName"

      - name: Create GitHub Release and upload artifact
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ inputs.tag_name  }}
          files: ${{ env.ZIP_NAME }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
